export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS';
export const CREATE_BUCKET = 'CREATE_BUCKET';
export const FETCH_BUCKETS_SUCCESS = 'FETCH_BUCKETS_SUCCESS';
export const DELETE_BUCKETS_SUCCESS = 'DELETE_BUCKETS_SUCCESS';
export const EDIT_BUCKETS_SUCCESS = 'EDIT_BUCKETS_SUCCESS';
export const CREATE_ITEM = 'CREATE_ITEM';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';



